---
- name: Some arch configuration
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install core tools
      become: true
      tags: [core]
      community.general.pacman:
        name:
          [
            base-devel,
            man-db,
            man-pages,
            git,
            net-tools,
            networkmanager,
            sudo,
            just,
            stow,
            lsof,
            fastfetch,
            tree,
            pass,
            tmux,
            lazygit,
            jq,
            fzf,
            ripgrep,
            tree-sitter,
            tree-sitter-cli,
            oath-toolkit,
            fd,
            sshfs,
            mkcert,
            rclone,
            neovim,
            lua51,
            rofi,
            htop,
            nvtop,
            nix,
            inetutils,
            openbsd-netcat,
            sops,
            udisks2,
            inotify-tools,
            dmidecode,
            miller,
            ghostty,
            timeshift,
            zsh,
            packer,
            ttf-jetbrains-mono-nerd,
          ]
        state: present
        update_cache: true

    - name: Check if yay is installed
      tags: [core, yay]
      ansible.builtin.stat:
        path: /usr/bin/yay
      register: yay_stat

    - name: Clone yay-bin from AUR
      tags: [core, yay]
      ansible.builtin.git:
        repo: "https://aur.archlinux.org/yay-bin.git"
        dest: "{{ ansible_facts['user_dir'] }}/yay"
        version: master
      when: not yay_stat.stat.exists
      check_mode: false

    - name: Build yay
      tags: [core, yay]
      ansible.builtin.command:
        cmd: makepkg -f --noconfirm
        chdir: "{{ ansible_facts['user_dir'] }}/yay"
      when: not yay_stat.stat.exists
      changed_when: true
      check_mode: false

    - name: Find the yay package file
      tags: [core, yay]
      ansible.builtin.find:
        paths: "{{ ansible_facts['user_dir'] }}/yay"
        patterns: "yay-*.pkg.tar.zst"
      register: yay_package
      when: not yay_stat.stat.exists
      check_mode: false

    - name: Install yay package
      tags: [core, yay]
      become: true
      ansible.builtin.command:
        cmd: "pacman -U --noconfirm {{ yay_package.files | map(attribute='path') | join(' ') }}"
      when: not yay_stat.stat.exists
      changed_when: true
      check_mode: false

    - name: Ensure yay target directory exists
      tags: [always]
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.config/yay"
        state: directory
        mode: "0755"
      changed_when: false
      check_mode: false

    - name: Stow yay configuration
      tags: [core, yay, dotfiles]
      ansible.builtin.command:
        cmd: stow -t "{{ ansible_facts['user_dir'] }}/.config/yay" yay
        creates: "{{ ansible_facts['user_dir'] }}}/.config/yay"
      changed_when: false

    - name: Install development tools
      become: true
      tags: [development]
      community.general.pacman:
        name:
          [
            docker,
            docker-compose,
            docker-buildx,
            mariadb-clients,
            go,
            golangci-lint,
            vault,
            github-cli,
            kubectl,
            nodejs,
            fluxcd,
            prettier,
            luarocks,
            htmlq,
            npm,
            yarn,
            namcap,
            moreutils,
            python-pandas,
            python-matplotlib,
            python-seaborn,
            ansible-lint,
          ]
        state: present
        update_cache: true

    - name: Install GPU tools
      become: true
      tags: [gpu]
      community.general.pacman:
        name: [nvidia-open]
        state: present
        update_cache: true

    - name: Install GNOME tools
      become: true
      tags: [gnome]
      community.general.pacman:
        name: [eog, gnome, gdm, wl-clipboard]
        state: present
        update_cache: true

    - name: Get UUID of the backup target partition
      tags: [always]
      ansible.builtin.command:
        cmd: findmnt -n -o UUID -T /
      register: target_drive_uuid
      changed_when: false
      check_mode: false

    - name: Ensure /etc/timeshift directory exists
      become: true
      tags: [core, etc]
      ansible.builtin.file:
        path: /etc/timeshift
        state: directory
        mode: "0755"
      check_mode: false

    - name: Copy /etc/timeshift/timeshift.json
      become: true
      tags: [core, etc, timeshift]
      ansible.builtin.template:
        src: ./etc/timeshift/timeshift.json.j2
        dest: /etc/timeshift/timeshift.json
        mode: "0644"
        backup: true

    - name: Enable cronie for timeshift
      become: true
      tags: [core, timeshift]
      ansible.builtin.systemd:
        name: cronie
        enabled: true

    - name: Copy /etc/pacman.conf
      become: true
      tags: [core, etc]
      ansible.builtin.copy:
        src: ./etc/pacman.conf
        dest: /etc/pacman.conf
        mode: "0644"
        backup: true

    - name: Generate SSH key
      tags: [core, ssh]
      become: true
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        generate_ssh_key: true
        ssh_key_type: ed25519
        ssh_key_file: .ssh/id_ed25519
