---
- name: Some arch configuration
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install core tools
      become: true
      tags: [core]
      community.general.pacman:
        name:
          [
            base-devel,
            man-db,
            man-pages,
            git,
            net-tools,
            networkmanager,
            sudo,
            just,
            stow,
            lsof,
            fastfetch,
            tree,
            pass,
            tmux,
            lazygit,
            jq,
            fzf,
            ripgrep,
            tree-sitter,
            tree-sitter-cli,
            oath-toolkit,
            fd,
            sshfs,
            mkcert,
            rclone,
            neovim,
            lua51,
            rofi,
            htop,
            nvtop,
            nix,
            inetutils,
            openbsd-netcat,
            sops,
            udisks2,
            inotify-tools,
            dmidecode,
            miller,
            ghostty,
            timeshift,
            zsh,
            packer,
            ttf-jetbrains-mono-nerd,
            keyd,
            firefox,
            socat,
            elvish,
            pv,
            himalaya,
            age,
            bc,
            devtools,
          ]
        state: present
        update_cache: true

    - name: Check if paru is installed
      tags: [core, paru]
      ansible.builtin.stat:
        path: /usr/bin/paru
      register: paru_stat

    - name: Clone paru from AUR
      tags: [core, paru]
      ansible.builtin.git:
        repo: "https://aur.archlinux.org/paru.git"
        dest: "{{ ansible_facts['user_dir'] }}/paru"
        version: master
      when: not paru_stat.stat.exists
      check_mode: false

    - name: Build paru
      tags: [core, paru]
      ansible.builtin.command:
        cmd: makepkg -f --noconfirm
        chdir: "{{ ansible_facts['user_dir'] }}/paru"
      when: not paru_stat.stat.exists
      changed_when: true
      check_mode: false

    - name: Find the paru package file
      tags: [core, paru]
      ansible.builtin.find:
        paths: "{{ ansible_facts['user_dir'] }}/paru"
        patterns: "paru-*.pkg.tar.zst"
      register: paru_package
      when: not paru_stat.stat.exists
      check_mode: false

    - name: Install paru
      tags: [core, paru]
      become: true
      ansible.builtin.command:
        cmd: "pacman -U --noconfirm {{ yay_package.files | map(attribute='path') | join(' ') }}"
      when: not yay_stat.stat.exists
      changed_when: true
      check_mode: false

    - name: Copy paru conf
      become: true
      tags: [core, etc, paru]
      ansible.builtin.copy:
        src: ./paru/paru.conf
        dest: /etc/paru.conf
        mode: "0644"
        backup: true

    - name: Create local AUR repository
      become: true
      tags: [core, paru]
      ansible.builtin.file:
        path: /var/lib/repo/aur
        state: directory
        mode: "0755"

    - name: Initialize local AUR repository
      become: true
      tags: [core, paru]
      ansible.builtin.command:
        cmd: repo-add /var/lib/repo/aur/aur.db.tar.gz
        creates: /var/lib/repo/aur/aur.db.tar.gz

    - name: Set local AUR repository ownership
      become: true
      tags: [core, paru]
      ansible.builtin.file:
        path: /var/lib/repo/aur
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        recurse: true

    - name: Install development tools
      become: true
      tags: [development]
      community.general.pacman:
        name:
          [
            docker,
            docker-compose,
            docker-buildx,
            mariadb-clients,
            go,
            golangci-lint,
            vault,
            github-cli,
            kubectl,
            nodejs,
            fluxcd,
            prettier,
            luarocks,
            htmlq,
            npm,
            yarn,
            namcap,
            moreutils,
            python-pandas,
            python-matplotlib,
            python-seaborn,
            ansible-lint,
            bats,
            gitleaks,
            slirp4netns,
          ]
        state: present
        update_cache: true

    - name: Install nvidia GPU tools
      become: true
      tags: [gpu, nvidia]
      community.general.pacman:
        name: [nvidia-open]
        state: present
        update_cache: true

    - name: Install AMD GPU tools
      become: true
      tags: [gpu, amd]
      community.general.pacman:
        name: [vulkan-radeon]
        state: present
        update_cache: true

    - name: Install GNOME tools
      become: true
      tags: [gnome]
      community.general.pacman:
        name: [eog, gnome, gdm, wl-clipboard]
        state: present
        update_cache: true

    - name: Get UUID of the backup target partition
      tags: [always]
      ansible.builtin.command:
        cmd: findmnt -n -o UUID -T /
      register: target_drive_uuid
      changed_when: false
      check_mode: false

    - name: Ensure /etc/timeshift directory exists
      become: true
      tags: [core, etc]
      ansible.builtin.file:
        path: /etc/timeshift
        state: directory
        mode: "0755"
      check_mode: false

    - name: Copy /etc/timeshift/timeshift.json
      become: true
      tags: [core, etc, timeshift]
      ansible.builtin.template:
        src: ./etc/timeshift/timeshift.json.j2
        dest: /etc/timeshift/timeshift.json
        mode: "0644"
        backup: true

    - name: Enable cronie for timeshift
      become: true
      tags: [core, timeshift]
      ansible.builtin.systemd:
        name: cronie
        enabled: true

    - name: Copy /etc/pacman.conf
      become: true
      tags: [core, etc]
      ansible.builtin.copy:
        src: ./etc/pacman.conf
        dest: /etc/pacman.conf
        mode: "0644"
        backup: true

    - name: Enable essential services
      become: true
      tags: [core]
      ansible.builtin.systemd:
        name: keyd
        enabled: true

    - name: Generate SSH key
      tags: [core, ssh]
      become: true
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        generate_ssh_key: true
        ssh_key_type: ed25519
        ssh_key_file: .ssh/id_ed25519
