name: ansible-lint
on:
  push:
  pull_request:
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v4

      - name: Install ansible-lint
        run: pipx install ansible-lint

      - name: Run ansible-lint
        run: just lint
